### ISSUE TITLE
Can I get recommendation on pods created by an operator?

### ISSUE THREAD

**Issue by peijianju** [FairwindsOps/goldilocks#138]
Hi, 

My apologies if this is not the right place to ask questions. Please point me to the right place.

I am wondering how can I have the resource recommendation if my pods are created by an operator instead of a deployment.

Specifically, I am using a database called ArangoDB, and its pods are created by operators, there is no deployment control the pods

Thanks a lot for the help.

Eric

**Comment by sudermanjr** [comment]
This is an interesting question. I believe that it would be possible to add to Goldilocks, however it will require some code changes.

There are currently plans to implement daemonsets and statefulsets which are in flight, but there is also a discussion about adding arbitrary controllers. However, I'm not certain how that would work in the case of an operator. My gut feeling is that something would have to be done at the VPA level, which is controlled by this repository - https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

You might consider asking there. I will look into as well once we get working on the additional controllers. @rbren or @lucasreed might have some ideas on this as well.

**Comment by lucasreed** [comment]
I'm also unsure how that would work, especially if VPA was set to update automatically without a parent controller known to the VPA tool. I would ask in the repository linked above by @sudermanjr
