### ISSUE TITLE
Use annotations instead of labels for namespaces

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/goldilocks#148]
There is a general desire to move to annotations. I think we should go this route:

1) Release a major version and add annotation support. Start warning about deprecation of labels.
2) At some later date, fully deprecate the labels. Release a minor or major version. TBD

**Comment by milanmayr** [comment]
I know annotations are commonly used by Kubernetes tools, but I think using labels is the right choice.

> Labels are for Kubernetes, while annotations are for humans.
> _- from [Kubernetes Annotations and Labels: What’s the Difference?](https://blog.getambassador.io/kubernetes-labels-vs-annotations-95fc47196b6d)_

**Comment by sudermanjr** [comment]
We currently use either annotations or labels I believe, so we can just close this.
