### ISSUE TITLE
Clarify the recommendation of not using the CLI?

### ISSUE THREAD

**Issue by kaihoffman** [FairwindsOps/goldilocks#165]
The heading and description for the CLI state it is not recommended for use. I can see the desire to have the application run alongside deployed pods but my first thought upon reading the heading was "why not?"

Adding a clarifying statement to the recommendation for the Dashboard over CLI would go a long way to assuage users as to why it's there.

**Comment by sudermanjr** [comment]
@kaihoffman Thanks for the feedback! 

I opened #166 to address this. Please let me know if that is a little more clear.

**Comment by kaihoffman** [comment]
Looks perfectly clear to me! Couldn't have asked for more tbh.
