### ISSUE TITLE
Namespace annotation updateMode does not work?

### ISSUE THREAD

**Issue by Alien2150** [FairwindsOps/goldilocks#176]
Hello,

maybe I am missing something but here is my problem: I changed the namespace label as mentioned on github in order to turn on "auto" mode. Now the namespace label's look like this:

labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-update-mode: Auto (Tried both "auto" and "Auto")

But all my already setup vpa’s still remain on the same mode. In order to resolve it I tried:
* Deleting the excisting vpa's
* Restarted the controller

Just let me know if I need to provide more information. 

Cheers,
Thomas

**Comment by sudermanjr** [comment]
What version of Goldilocks did you install? The updateMode stuff hasn't been released, so if you want to use the experimental versions you'll have to pin to master or a specific SHA.

**Comment by Alien2150** [comment]
I used Helm fetch (2-3 days ago). I also took the steps from the GitHub readme.md is that not consistent?

**Comment by Alien2150** [comment]
Turned out that the documentation is newer than my currently version. Looking forward for the new release :)
