### ISSUE TITLE
re-implement the base-path option correctly

### ISSUE THREAD

**Issue by mindw** [FairwindsOps/goldilocks#185]
Unlike FairwingsOps/polaris `--base-path` has no effect.

How to reproduce (v2.2):
1. run dashboard with `--base-path=/goldilocks/` 
2. Try accessing `localhost:8080/goldilocks/`

Expected:
* goldilocks GUI shows.

Actual:
* 404 error from goldilocks.

**Comment by mindw** [comment]
Err, activity?

**Comment by chgl** [comment]
Running into the same issue when deploying via the Helm Chart. Polaris works nicely with a custom `basePath` so looking at the differences between the two implementations should help determine the root cause.

**Comment by davidcalleja** [comment]
I have the same issue. After set this variable, all static url changed but goes to 404

**Comment by sudermanjr** [comment]
I'll try to get this on the Q4 roadmap. Thanks for the updates!

**Comment by mindw** [comment]
Whomp! 👊🏻

**Comment by sudermanjr** [comment]
As far as I can tell this never worked, so we are removing it in a current PR, and I am converting this to a feature request to re-implement.

**Comment by lduparc** [comment]
Hi, 

Any news about it ?
Or similar option using Helm ?

Thanks

**Comment by dorroddorrod** [comment]
Hi guys,
Any updates ? i'm not able to use the goldilocks dashboard due to this missing feature. (working with path based routing)

**Comment by mindw** [comment]
Please? 🙏🏻 with 🍬 ?

**Comment by sudermanjr** [comment]
Currently we don't have the bandwidth to tackle this internally. If there's anyone in the community who would like to contribute, we would welcome the contribution!
