### ISSUE TITLE
Recommend < 250Mi for memory request

### ISSUE THREAD

**Issue by oskapt** [FairwindsOps/goldilocks#210]
It seems that the minimum recommended memory request is 250Mi, even if the app is regularly using less than that. How is this calculated? Is it configurable?

**Comment by sudermanjr** [comment]
This is a setting in the vertical pod autoscaler recommender that you can pass as a flag:

```
└─ docker run us.gcr.io/k8s-artifacts-prod/autoscaling/vpa-recommender:0.8.0 --help
pflag: help requested
Usage of /recommender:
...
      --pod-recommendation-min-memory-mb float        Minimum memory recommendation for a pod (default 250)
...
```

**Comment by oskapt** [comment]
Ok. The VPA is being installed by Goldilocks, so where do I configure this? It's not in the Helm chart. There doesn't appear to be a ConfigMap for the VPA in kube-system either.

**Comment by sudermanjr** [comment]
In this case we recommend you manage the VPA install outside of the Goldilocks install. The chart does not currently support customizing the VPA install.

Since VPA is still relatively "beta" they don't have a great install process in place.  The flag would be set directly in the deployment configuration.

**Comment by oskapt** [comment]
Hmm. Okay. One of the nice features of your app is that it performs the VPA install automatically in recommendation mode. I hope that you're able to get some tuning in for that in the future.

**Comment by sudermanjr** [comment]
My hope is to eventually just write an actual configurable VPA chart and use it as a sub-chart for Goldilocks. Unfortunately that's low on the priority list right now.
