### ISSUE TITLE
add support for Argo rollouts

### ISSUE THREAD

**Issue by smitthakkar96** [FairwindsOps/goldilocks#217]
We use Argo Rollouts for our Web App and instead of deployment we create Rollout  object. Do you think it is possible to make it work with Rollouts with current implementation, if not are you guys open to the idea of adding support for Rollouts?

I was also thinking is there a way to have a generic implementation that supports various kind of objects like statefulsets, deployments, argo-rollouts etc.

**Comment by sudermanjr** [comment]
I know we currently have issues in for supporting more controller types. I believe we can roll all of those up to support all pod controller types, based on the way the selectors work in VPA.

**Comment by sudermanjr** [comment]
closing in favor of #225
