### ISSUE TITLE
Pods not appearing in the dashboard

### ISSUE THREAD

**Issue by zhaocheng173** [FairwindsOps/goldilocks#224]

**Comment by rbren** [comment]
Copied from the original title:
```
When I could open all the namespaces, I had sensed the VPA of the VPA from my previous POD. After I added a POD later, I checked the dashboard again but found no new POD listed on the dashboard
```

Could you add some more details, specifically the commands you ran?

**Comment by sudermanjr** [comment]
Could be related to https://github.com/FairwindsOps/goldilocks/issues/216

**Comment by zhaocheng173** [comment]
This is in my Test namespace, and this is the dashboard list. There's no POD running yet, but the test namespace is already open
`Namespace: test`

Enabled under the Test namespace
```
# kubectl get ns --show-labels
NAME              STATUS   AGE     LABELS
default           Active   21d     goldilocks.fairwinds.com/enabled=true
goldilocks        Active   24h     goldilocks.fairwinds.com/enabled=true
kkkk              Active   20h     goldilocks.fairwinds.com/enabled=true
kube-node-lease   Active   21d     goldilocks.fairwinds.com/enabled=true
kube-public       Active   21d     goldilocks.fairwinds.com/enabled=true
kube-system       Active   21d     goldilocks.fairwinds.com/enabled=true
polaris           Active   20h     goldilocks.fairwinds.com/enabled=true
test              Active   5d22h   goldilocks.fairwinds.com/enabled=true
```
I am not currently creating the POD resource under the Test namespace
```
# kubectl get pod -n test
No resources found in test namespace.
```
Now I'm going to create a POD under the Test namespace
```
# kubectl apply -f test-busybox.yaml 
pod/busybox-test created
[root@master goldilocks]# kubectl get po -n test
NAME           READY   STATUS    RESTARTS   AGE
busybox-test   1/1     Running   0          8s
```

When I checked my dashboard again, the list was still empty
This place shows only my Test namespace, but not the POD I created
`Namespace: test`

**Comment by sudermanjr** [comment]
Goldilocks will only currently report on Deployments, not "naked pods".  The practice of creating single pods without a controller is strongly discouraged.
