### ISSUE TITLE
Namespace List Incomplete

### ISSUE THREAD

**Issue by isugimpy** [FairwindsOps/goldilocks#236]
After turning on the functionality to create VPAs in all namespaces, I noticed most of mine don't show up in the list.  Digging into the code, I discovered the namespace list only returns namespaces which contain the label.  This seems undesirable, as going into all namespaces returns everything.  Should this, instead, check if the label is false, and if it's true or unset enumerate the VPAs to decide if it should be returned?

**Comment by sudermanjr** [comment]
Thanks for bringing this to our attention. The flag should probably just be added to the dashboard as well in order to disable that filtering.

**Comment by isugimpy** [comment]
I've opened a pull request for this issue, hopefully it can be brought in and released fairly quickly, as it's a pretty small change for a big value add.
