### ISSUE TITLE
Vpa recommendation extend timeline/ use prometheus instead?

### ISSUE THREAD

**Issue by pgold30** [FairwindsOps/goldilocks#252]
We got some recommendations from vpa based on usage , but historically from prometheus 30 days query we get for example 2Gb of usage , normal is 25 Mi and recommedation from goldilocks is around that, how can we extend the query for vpa or use prometheus instead with a bigger datetime so we can be sure what is the peak and put that as a limit?

**Comment by sudermanjr** [comment]
If you're already using prometheus with VPA I'm not sure how to do that. This might be better asked in the autoscaler rep.

**Comment by sudermanjr** [comment]
If you haven't already hooked up your VPA to prometheus, there's a section in their FAQ about it https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md

**Comment by pgold30** [comment]
Thanks! our prometheus contains only 24h , we use thanos for longer storage , do you know if this is compatible with that? otherwise s3 or how would u use a bigger timeframe?

**Comment by sudermanjr** [comment]
I honestly have no clue about Thanos. I would recommend reaching out the folks in the autoscaler repo.
