### ISSUE TITLE
--exclude-namespaces with a list of ns does not work

### ISSUE THREAD

**Issue by reggie-k** [FairwindsOps/goldilocks#268]
This works(indeed excluded):
- --on-by-default
- --exclude-namespaces=openshift-apiserver

This does not (meaning both ns get vpa created while both should be excluded)
- --on-by-default
- --exclude-namespaces=openshift-apiserver,openshift-apiserver-operator

**Comment by sudermanjr** [comment]
Good catch! I'll have a fix in shortly.
