### ISSUE TITLE
Postgresql Pod doesn't show up at Goldilocks

### ISSUE THREAD

**Issue by neolunar7** [FairwindsOps/goldilocks#288]
Hi, Postgresql Pod doesn't show up at Goldilocks, any known reasons?

**Comment by sudermanjr** [comment]
Can you please provide a bit more information?

Configuration, version, kubectl output showing the error, and steps to reproduce would all be helpful.

**Comment by neolunar7** [comment]
First of all,

**Comment by neolunar7** [comment]
The Helm Chart version I'm using is 3.1.0, from https://github.com/FairwindsOps/charts/tree/master/stable/goldilocks

**Comment by neolunar7** [comment]
As I have just installed the default Helm Chart without any additional configurations, and the issue I'm facing is not an error, I cannot provide kubectl logs or so.

**Comment by baderbuddy** [comment]
I believe Goldilocks right now only monitors Deployments not StatefulSets. So that would explain it.

**Comment by neolunar7** [comment]
@baderbuddy Oh, that explains it. It's weird though. Is there a doc where it says Statefulsets are not supported ?

**Comment by sudermanjr** [comment]
It should be in the docs, but if not we are tracking the issue in #225
