### ISSUE TITLE
Avoid creating Goldilocks managed VPA if a VPA already exists

### ISSUE THREAD

**Issue by max0ne** [FairwindsOps/goldilocks#303]
If for a deployment object, a VPA already exists before goldilocks installed, would goldilocks create another VPA for this deployment object?

I didn't see this mentioned in the docs, and by reading through the code it seems goldilocks ignores VPAs that doesn't have `VPALabels` in labels, so my understanding is yes goldilocks will create VPAs in this case.

This is a concern for a usecase that some legacy VPAs are already installed in cluster, and goldilocks is installed, and some duplicated VPAs are installed, which is [bad according to vertical-pod-autoscaler known limitations](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#known-limitations): 
> Multiple VPA resources matching the same pod have undefined behavior.

Furthermore goldilocks should also avoid creating VPAs for deployments that have CPU or memory based HPAs configured:
> Vertical Pod Autoscaler should not be used with the Horizontal Pod Autoscaler (HPA) on CPU or memory at this moment. However, you can use VPA with HPA on custom and external metrics.

**Comment by oba11** [comment]
Interested in this as well because we do have some services that already has VPA defined and we would like not to duplicate resources

**Comment by dvic** [comment]
I just deployed goldilocks and I had a VPA for a particular deployment, it did not create another VPA. It did create one for a deployment that was missing a VPA, so this seems to working? I did have to add 
```yaml
  labels:
    creator: Fairwinds
    source: goldilocks
```
to the VPA to make it appear in the dashboard.
