### ISSUE TITLE
Initial setup issue.

### ISSUE THREAD

**Issue by igorpalant** [FairwindsOps/goldilocks#311]
I have installed Goldilocks using following instructions and labeled targeted namespaces: https://www.fairwinds.com/blog/introducing-goldilocks-a-tool-for-recommending-resource-requests
I see list of deployments in Goldilocks dashboard, but no data on the deployments. Am I missing something? No errors in the goldilocks-controller container.

**Comment by sudermanjr** [comment]
Do you have the `metrics-server` installed? What do the individual VPA objects that are associated with the deployments look like? They should have a status field with `recommendations` in them

This FAQ section might help https://goldilocks.docs.fairwinds.com/faq/#i-am-not-getting-any-recommendations-what-gives

**Comment by igorpalant** [comment]
Thanks, I do have metrics-server installed and I checked it according to FAQ you provided. I do see verticalpodautoscalers created for each deployment in namespace but when I describe them, I do not see recommendations
