### ISSUE TITLE
Use of equals sign in UI is confusing/wrong

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [FairwindsOps/goldilocks#316]
This doesn't look correct to me. The values are not equal, but there is an equals sign:

https://ipfs.io/ipfs/QmdUqxp3kqcxCR9GbKJhjvadZnVwUT1gcJ4rrfg5zeLe6m?filename=Screenshot%20from%202021-06-08%2014-20-09.png

See discussion in the Fairwinds slack here:

https://fairwindscommunity.slack.com/archives/CV0AU2CTS/p1623187253001500

Perhaps we should be using the "approximately equals" symbol `≈` instead?

LOL: https://youtu.be/dTRKCXC0JFg

**Comment by evanstucker-hates-2fa** [comment]
Even so, I see `900m = 60m` which is over an order of magnitude larger. That really isn't even approximately equal.

**Comment by Fodoj** [comment]
I see the same issue, equal sign does not seem to make any sense in the dashboard

**Comment by sudermanjr** [comment]
We will have to look at this and determine if it's a bug or just an issue with confusing definitions on burstable QoS class.

**Comment by kyranb** [comment]
I've seen the same thing 👀

Caught me by surprise as the numbers are definitely not the same.

**Comment by HariSekhon** [comment]
I'm seeing the same bug:

![Screenshot 2022-10-28 at 14 31 37](https://user-images.githubusercontent.com/2211051/198612504-a3333fdd-520d-4812-bf24-531e88f34dd0.png)

**Comment by sudermanjr** [comment]
I'm going to tackle at least part of this during the next CNCF livestream on March 1st 2023.
