### ISSUE TITLE
Add namespace flag to summary command

### ISSUE THREAD

**Issue by stephanGarland** [FairwindsOps/goldilocks#320]
If you have a lot of namespaces across multiple clusters, it's nice to be able to see what identical pods in different environments need - performing statistical analysis would be a huge perk, but if nothing else, being able to dump a cluster's dashboards into YAML or JSON would be nice.

I wrote [a scraper](https://github.com/stephanGarland/goldilocks-scraper) to accomplish this, but having it integrated would be really great.

**Comment by sudermanjr** [comment]
What if we just added an all namespace flag to the summary command so that we can output the JSON for all namespaces?

**Comment by stephanGarland** [comment]
That would be fantastic, thank you.

**Comment by ctml91** [comment]
Are the recommenders metrics exported to prometheus already? If so I imagine we could query it to fetch the data. If not, that would be the ideal solution imo.

**Comment by sudermanjr** [comment]
This has been done.
