### ISSUE TITLE
oidc support

### ISSUE THREAD

**Issue by kfox1111** [FairwindsOps/goldilocks#322]
It would be nice if goldilocks website could utilize an oidc token to perform all actions for the user, so it can be safely used on a soft multi tenant cluster.

**Comment by sudermanjr** [comment]
Is this something that client-go can do by default, or would we need to build something ourselves?

**Comment by kfox1111** [comment]
The kubernetes dashboard takes in the oidc token as an http header, and then passes it as the kube auth token for all client requests from that user to the apiserver. You can then setup oauth2_proxy or something in front to do the actual oidc auth and pass the token to the dashboard. Then the website only can perform actions of the user thats logged into it, honoring kubernetes rbac. I'd think goldilocks could do something similar.

**Comment by sudermanjr** [comment]
This is a really interesting request, but this is currently outside of our scope of potential work due to the large amount of work that would have to go into building and maintaining it. Thanks for the suggestion!
