### ISSUE TITLE
Support additional properties on VPAs like ResourcePolicy

### ISSUE THREAD

**Issue by kengibous** [FairwindsOps/goldilocks#374]
It would be great if there was some additional labels available that could configure certain VPA features such as the ResourcePolicy for the VPAs

A resource policy contains container policies that allow you to exclude/include specific containers from the updateMode, set min/max allowed cpu and memory.  They also allow setting the controlledValues property which can tell the VPAs to set requests and limits (RequestsAndLimits) or requests only (RequestOnly)

These can all be very helpful when needing to have more flexibility 

Some good reference articles

https://povilasv.me/vertical-pod-autoscaling-the-definitive-guide/
https://betterprogramming.pub/understanding-vertical-pod-autoscaling-in-kubernetes-6d53e6d96ef3

I would be happy to work on adding this - if this is appropriate for this project.

Thank you!

**Comment by lucasreed** [comment]
Hey there @kengibous thanks for this suggestion! We've been having some discussion in the community slack about this and are considering adding annotations for the full VPA spec to allow more flexibility. We will talk more and come up with a plan.

**Comment by kengibous** [comment]
@sudermanjr excellent, I will add details to the advanced usage docs as well.

@lucasreed thanks for the heads up, I will do that!

**Comment by kengibous** [comment]
Created PR - https://github.com/FairwindsOps/goldilocks/pull/375
