### ISSUE TITLE
Controller OOMKilled - set higher default memory limits

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/goldilocks#392]
I've deployed Goldilocks from both master git manifests and Helm chart 4.0.2 and both set the memory limits to 32M resulting in the pod crashing with `OOMKilled` and the `Error running summary` message in the dashboard web page as per #386.

This is even just running against the goldilocks namespace itself, not even running against my real substantial microservices.

I recommend setting a higher default memory request and limit - Goldilocks recommended 160Mi to me, and that's before setting it to task on all my apps.

**Comment by sudermanjr** [comment]
In my operations cluster install I only use about 16Mi of memory at any given time on the dashboard. Resource needs will be highly dependent on your cluster topology, and we recommend that you set them accordingly. The default values file resources are only meant to be a starting point.

**Comment by HariSekhon** [comment]
I agree this is dependent on deployment and numbers of apps, but given mine was dying at the 32M limit for just the Goldilocks namespace with only Goldilocks in it at that time, I'm surprised yours was ok with 16Mi - might it still be worth setting a slightly highly memory default?

Perhaps a memory request of 64Mi or 128Mi and higher memory limit such as 256Mi will allow Goldilocks to be more likely to work in most cases even for users who haven't tuned it, in order for Goldilocks to run long enough for people to self-tune based on the Goldilocks findings?

**Comment by ctrought** [comment]
I'd tend to agree, 16Mi seems to be okay for bare minimum install. If you plan to have goldilocks manage more than a handful of VPAs you likely need to bump it up quite a lot. In my case I'm seeing the controller using the below based on the number of VPAs in each cluster. In any case it's going to differ for every cluster so it might still make sense for everyone to tune based on the number of VPAs they are creating... Or perhaps we can enable a VPA in auto mode for the controller itself :) ?

70 VPAs = ~200Mi
400 VPAs = ~512Mi

**Comment by sudermanjr** [comment]
You could definitely add a VPA in auto mode for the controller. I would happily approve a PR to the chart to make this an option (default off)
