### ISSUE TITLE
4.1 Helm Chart availability?

### ISSUE THREAD

**Issue by HariSekhon** [FairwindsOps/goldilocks#400]
4.1 has been out for a few days now, any ETA on when the 4.1 helm chart will be released?

I've been checking here:

https://artifacthub.io/packages/helm/fairwinds-stable/goldilocks

I'm waiting on this to solve the VPA naming clash across various production namespaces.

For now I've just worked around with a `values.yaml` override on the image tag which has worked but would obviously prefer to get rid of this before I forget as otherwise it may interfere with future chart version upgrades:
```
image:
  tag: v4.1.0  # XXX: temporary override until new Helm chart is out to get non-clashing prefixed VPAs
```

**Comment by lucasreed** [comment]
:wave: Hey @HariSekhon it's on our list to do, but no ETA currently.

**Comment by HariSekhon** [comment]
Ok thanks for letting me know, I've worked around the image version as per above so no rush now, I just don't want to forget about this hack as a future helm chart image version may get downgraded with this left in there.

**Comment by sudermanjr** [comment]
Looks like this has been completed https://github.com/FairwindsOps/charts/pull/645

In the future, can you please file issues specifically with the chart in the charts repository?
