### ISSUE TITLE
Provide opencontainers labels in Dockerfile

### ISSUE THREAD

**Issue by mstoetzer** [FairwindsOps/goldilocks#410]
It could be a nice addition to provide official opencontainers labels in the Dockerfile of goldilocks:

```
LABEL org.opencontainers.image.authors="xxxx" \
      org.opencontainers.image.source="https://github.com/FairwindsOps/goldilocks" \
      org.opencontainers.image.description="Goldilocks is a utility that can help you identify a starting point for resource requests and limits." \
      org.opencontainers.image.documentation="https://goldilocks.docs.fairwinds.com/" \
      org.opencontainers.image.licenses="Apache License 2.0" \
      org.opencontainers.image.title="goldilocks" \
      org.opencontainers.image.url="https://github.com/FairwindsOps/goldilocks" \
      org.opencontainers.image.vendor="FairwindsOps"
```

One example why this is useful is dependabot or renovatebot. When these tools update the dockerimage version, they can extract the release notes from the `source` label and provide it in the pullrequest. [See the renovate docs](https://github.com/renovatebot/renovate/blob/4b6270b981612f1108d23c3fbe0f85ed28f2ca18/lib/datasource/docker/readme.md)

What do you think?

**Comment by hummelh** [comment]
+1

For reference:
https://github.com/opencontainers/image-spec/blob/main/annotations.md
