### ISSUE TITLE
Support for HPA

### ISSUE THREAD

**Issue by jainpratik163** [FairwindsOps/goldilocks#419]
hi,
does Goldilocks support HPA as we don't have VPA.
if yes then how we can configure with HPA.

Thanks

**Comment by sudermanjr** [comment]
We do not support HPA. That wouldn't really fit within the scope of what Goldilocks is trying to do. Please take a look at our documentation where we describe the goal of the project and how it works: https://goldilocks.docs.fairwinds.com/#how-can-this-help-with-my-resource-settings

Thanks!

**Comment by jpelletier1** [comment]
Hi @jainpratik163, thanks for the question! While it doesn't fit into Goldilocks today, I'd love to better understand your challenges around HPA. What were you looking for originally with your question? What's challenging you today?

Thanks!
Joe
Fairwinds Product Manager

**Comment by jainpratik163** [comment]
@jpelletier1 I was looking same recommendation in the case of HPA as we are using HPA.
in our env we use HPA and on that basis, we are doing manual analysis and increasing the replicas of PODs, so we want some tools which give recommendations automatically.

**Comment by jpelletier1** [comment]
Thanks for the background! Makes sense - while not something in-scope yet for the open source, we are looking to better understand the challenges of our users.

Can you tell me a little more about your process today for figuring out replicas and scaling metrics?

**Comment by jainpratik163** [comment]
@jpelletier1 as I already mentioned we are using HPA and manually we are running this command `kubectl get hpa ` and on that basis, we are updating replicas manually and this is why we want some automatic tool which recommends us.
sometimes we also use grafana and Prometheus as a monitoring tools.
