### ISSUE TITLE
Goldilocks controller not excluding specific containers.

### ISSUE THREAD

**Issue by yonicurv** [FairwindsOps/goldilocks#436]
Hello,

1. We have implemented fairwinds goldilocks controller and dashboard v4.2.0 in our cluster, currently with monitor only.

2. The workloads seems to function properly (creates VPA), but we are getting errors that the controller can not watch / list daemonsets (No permissions):

 "msg"="An error occured retrieving the top level controller for this pod" "error"="daemonsets.apps is forbidden: User \"system:serviceaccount:xxxxx" cannot list resource \"daemonsets\" in API group \"apps\" in the namespace \"default\""  "xxxx"="default"

3. After allowing (using RBAC) the workload to watch and list also daemonsets we noticed that it also created VPA for the datadog-agent which is deployed across our cluster (as a daemonset). - which is not a desired result, and would like to exclude it from being monitored.

4. After trying to use to use the flag --exclude-containers (at the controller entrypoint) in order to skip VPA creation for specific containers, I noticed that it does not affect the behavior of the controller and still the datadog-agent VPA is being created.

I tried also labeling the specific resource of datadog daemonset with : goldilocks.fairwinds.com/exclude-containers=datadog-agent but did not help either.
The Goldilocks image version im using is 4.2.0
(https://github.com/FairwindsOps/goldilocks/releases)

 Is there any alternative way to exclude specific deployment / daemonset with goldilocks after it has permissions to list it ?

The only way it can be achieved now is by not allowing any access to daemonsets but this will cause the error logs to be flooded as shown at section 2.

Thank you,
Regards,
Yonatan.

**Comment by lucasreed** [comment]
Hello @yonicurv 👋 I think the label should work, but in datadog the container is not the same as the pod name. I think the container gets named `agent` by default. Could you try applying the following label to the daemonset: `goldilocks.fairwinds.com/exclude-containers=agent`

**Comment by yonicurv** [comment]
I can confirm that also after testing the exclusion suggested (label the daemonsets) and also after trying to exclude with dashboard entrypoint (--exclude-containers=agent), it still creates vpa for that container.

Any help would be appriciated.
Thanks.

**Comment by sudermanjr** [comment]
I think, looking at the code, that we support annotations on the controller, not labels:

https://github.com/FairwindsOps/goldilocks/blob/3675bc5b49e6e37e7caa5f2daec3954912ed1db9/pkg/summary/summary.go#L171-L173
