### ISSUE TITLE
Creating VPA on ReplicationControllers instead of DeploymentConfigs

### ISSUE THREAD

**Issue by uselessidbr** [FairwindsOps/goldilocks#438]
### What happened?

When label "goldilocks.fairwinds.com/enabled=true" is applied at a Namespace that contains DeploymentConfigs, Goldilocks is creating VPAs for ReplicationControllers instead of DeploymentConfig which is the top-level controller. What is causing this error in the generated VPAs:

`"The targetRef controller has a parent but it should point to a topmost well-known or scalable controller"`

### What did you expect to happen?

VPA being generated for the DeploymentConfigs instead of ReplicationControllers

### How can we reproduce this?

Creating a label "goldilocks.fairwinds.com/enabled=true" at a Namespace that contains DeploymentConfigs

### Version

4.1.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Running OKD 4.9 with VPA installed via HelmChart

**Comment by ctrought** [comment]
Do you see any RBAC errors in the controller log? The helm chart doesn't come with a cluster role that would provide it access to controllers not in apps/v1 or argoproj (if enabled in helm) out of box.

It works in our OpenShift environment with namespace labels on deployment configs, but we had to create the cluster role ourselves to provide the goldilocks controller access.

The helm chart includes an option for defining extra rules for the cluster role as well which you can use `controller.rbac.extraRules`.

**Comment by lucasreed** [comment]
👋  @uselessidbr, @ctrought is correct, at the surface this sounds like an RBAC issue, can you confirm that this fixed things?

**Comment by lucasreed** [comment]
I'm going to close this, but if the issue comes back up let us know.
