### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by ws-prive** [FairwindsOps/goldilocks#447]
Hi,

We want to see the recommendation etc for deployments, jobs etc which are already finished or deleted. We are using Keda to schedule pipelines, but are not able to see the used and recommendation of finished jobs.

Is there any way already to see historical data?

**Comment by ws-prive** [comment]
Ok, thanks

**Comment by ctml91** [comment]
@Evantage-WS you can get historical data for vpa recommendations by installing Kube State metrics, enabling VPA metrics and have Prometheus scraping it with cluster monitoring. The VPA data can then be queried via Prometheus and the retention will be defined there

**Comment by Evantage-WS** [comment]
> 

Hi @ctml91, thanks for the tip, I will look into it
