### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by sedatsencan** [FairwindsOps/goldilocks#451]
### What happened?

When I applied "kubectl label ns default goldilocks.fairwinds.com/enabled=true" in the default namespace where all my deployments are, the dashboard became inaccessible.

Error appearing in port forward log;
`E0331 15:41:26.411620   34508 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 2e99a25a80bbfc0799834ebe90229d1957f2babcb38d767a1a83d77d2c41799e, uid : exit status 1: 2022/03/31 15:41:26 socat[4876] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
E0331 15:41:26.413603   34508 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 2e99a25a80bbfc0799834ebe90229d1957f2babcb38d767a1a83d77d2c41799e, uid : exit status 1: 2022/03/31 15:41:26 socat[4877] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8080
E0331 15:41:26.505404   34508 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 2e99a25a80bbfc0799834ebe90229d1957f2babcb38d767a1a83d77d2c41799e, uid : exit status 1: 2022/03/31 15:41:26 socat[4878] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused`

**The number of deployments in the default namespace is 26. By the way, works fine on the goldilocks namespace with 2 example deployments.**

### What did you expect to happen?

It should work successfully on its default namespace (with a lot of deployments) as well.

### How can we reproduce this?

"kubectl label ns default goldilocks.fairwinds.com/enabled=true"

### Version

goldilocks: v4.3.1 , vpa: 0.10.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The dashboard works but crashes when I click on the default namespace.

**Comment by sudermanjr** [comment]
Can you verify that the dashboard pod is still running? The only thing I can think here is that maybe the dashboard got OOMKilled .

**Comment by sedatsencan** [comment]
Yeap! The default limit values are too low. I think it was fixed when I increased them. Thanks.
