### ISSUE TITLE
VPA frequent reconcile

### ISSUE THREAD

**Issue by ctml91** [FairwindsOps/goldilocks#459]
First of all I'd like to say a big thanks for the fantastic operator, it's a very important piece of our stack for helping to size workloads as we have a large number of workloads and managing those VPAs manually is quite a monstrous task. 

Because we have a high number of workloads & VPAs, we're noticing goldilocks to be a top consumer of the kubernetes API. We are using labelling of namespaces to enable VPAs in recommend mode for all workloads. After reviewing the logs of the controller I can see that the reconciliation is quite regular across the entire cluster (actually it is non-stop). I am trying to understand what logic the controller uses to determine whether reconciliation is necessary and if there is any way to limit that. You can imagine a cluster with 500+ namespaces, and 3000+ workloads/controllers those reconciliations put a bit of strain on the API, nothing too significant where we see impact but considering it is constant we are being proactive and seeing if there is anything that can be done as we like to be conscious of the kube API health as it is obviously a critical part of the overall cluster.

Are these reconciles done on a regular interval or are they done because something with the underlying object being watched has changed? (e.g. namespace labelled, vpa object modified, workload controller labelled/added/removed)

If the former, could I suggest increasing the reconciliation loop timer for larger environments (e.g. optional flag)?

If the latter, then I will need to dig into what is updating those resources so regularly! At the same time, if nothing has changed in terms of namespace labels it would be good if the controller knew and would skip reconciliation in the namespace.

As I typed this up, I scanned over the logs and see these prior to **some** of the reconciliation which to me makes me think these occurrences are the former and goldilocks is only responding to an update on an object it is watching (namespace in this case). In this case, should it skip reconciling everything in the NS if the NS labels have not changed and something unrelated to VPAs updated the NS?
 
```
I0420 13:30:38.809693       1 namespace.go:35] Namespace example-ns updated. Check the labels.
I0420 13:30:38.858944       1 vpa.go:268] There are 7 vpas in Namespace/example-ns
I0420 13:30:38.911726       1 vpa.go:181] Reconciling Namespace/example-ns for DeploymentConfig/workload1 with VPA/goldilocks-workload1
I0420 13:30:38.921156       1 vpa.go:324] Updated VPA/workload1 in Namespace/example-ns
I0420 13:30:38.921166       1 vpa.go:181] Reconciling Namespace/example-ns for DeploymentConfig/workload2 with VPA/goldilocks-workload2
I0420 13:30:39.009729       1 vpa.go:324] Updated VPA/workload2 in Namespace/example-ns
I0420 13:30:39.009747       1 vpa.go:181] Reconciling Namespace/example-ns for DeploymentConfig/workload3 with VPA/goldilocks-workload3
I0420 13:30:39.017268       1 vpa.go:324] Updated VPA/workload3 in Namespace/example-ns
I0420 13:30:39.017280       1 vpa.go:181] Reconciling Namespace/example-ns for DeploymentConfig/workload4 with VPA/goldilocks-workload4
I0420 13:30:39.060729       1 vpa.go:324] Updated VPA/workload4 in Namespace/example-ns
I0420 13:30:39.060743       1 vpa.go:181] Reconciling Namespace/example-ns for DeploymentConfig/workload5 with VPA/goldilocks-workload5
I0420 13:30:39.109168       1 vpa.go:324] Updated VPA/workload5 in Namespace/example-ns
I0420 13:30:39.109182       1 vpa.go:181] Reconciling Namespace/example-ns for CronJob/workload6 with VPA/goldilocks-workload6
I0420 13:30:39.163024       1 vpa.go:324] Updated VPA/workload6 in Namespace/example-ns
I0420 13:30:39.163052       1 vpa.go:181] Reconciling Namespace/workload7  for DeploymentConfig/workload7 with VPA/goldilocks-workload7
I0420 13:30:39.221953       1 vpa.go:324] Updated VPA/workload7 in Namespace/example-ns
```

However far more of the reconciliations look like this, where first there is either an error, or sometimes no error and nothing preceding to indicate why it is being reconciled. That makes me think it may be a mix of scheduled reconciliation and triggered, **or** that error `"Object has unknown type of <nil>"` is related to something causing this frequent reconciliation.

```
E0420 14:50:40.800254       1 handler.go:41] Object has unknown type of <nil>
E0420 14:50:40.800265       1 handler.go:41] Object has unknown type of <nil>
I0420 14:50:40.878712       1 vpa.go:268] There are 71 vpas in Namespace/example-ns2
# ... reconcile all 71 vpas
# ...
# ...
# ... reconcile some other namespaces
# ...
# ... another reconcile of example-ns2 15 seconds after previous one, no error preceeding and no message about NS updated
I0420 14:50:55.128292       1 vpa.go:268] There are 71 vpas in Namespace/example-ns2 
```
During reconcile, there are some RBAC related errors which I completely understand. Goldilocks has not been given to permissions to read clusterserviceversions which are a part of OLM. This is just an example of 1 object goldilocks does not have permissions to, most are CRD's from operators such as the ones mentioned below (grafana, prometheus). Personally I am okay with goldilocks not having permission to the top most controller, as long as it can see the child deployment/statefulset/controller which it does just fine! I suppose this is because the namespace is labelled, so it's trying to see if it is a controller it should create a VPA for, in the case of CSV's since they are OLM provided (and reconciled) I don't need/want it to watch over it. I don't care if it throws an RBAC error, as long as it doesn't think it is an unexpected error and tries to reconcile the namespace again (not clear if that is happening, but hopefully someone can tell me if that might be what is).

```
E0420 14:51:01.621073       1 controller.go:169]  "msg"="Error retrieving parent object" "error"="clusterserviceversions.operators.coreos.com is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"clusterserviceversions\" in API group \"operators.coreos.com\" in the namespace \"example-ns2\""  "v1alpha1"="clusterserviceversions"
E0420 14:51:01.621103       1 controller.go:64]  "msg"="An error occured retrieving the top level controller for this pod" "error"="clusterserviceversions.operators.coreos.com is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"clusterserviceversions\" in API group \"operators.coreos.com\" in the namespace \"example-ns2\""  "grafana-operator-controller-manager-68567"="example-ns2"
E0420 14:51:01.631381       1 controller.go:169]  "msg"="Error retrieving parent object" "error"="clusterserviceversions.operators.coreos.com is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"clusterserviceversions\" in API group \"operators.coreos.com\" in the namespace \"example-ns2\""  "v1alpha1"="clusterserviceversions"
E0420 14:51:01.631405       1 controller.go:64]  "msg"="An error occured retrieving the top level controller for this pod" "error"="clusterserviceversions.operators.coreos.com is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"clusterserviceversions\" in API group \"operators.coreos.com\" in the namespace \"example-ns2\""  "prometheus-operator-79b78d"="example-ns2"
```

Thanks in advance!

**Comment by sudermanjr** [comment]
Hi! Thanks for the detailed report, sorry this didn't get picked up sooner. 

In order to support all top-level controllers such as daemonsets, statefulsets, etc, Goldilocks now watches for all pods in a cluster and then looks up their top-level controller. I do see how this could cause a lot of traffic in very large clusters. 

This also explains the errors for the other CRDs - Goldilocks is attempting to look them up because they are the owners of a pod.

**Comment by mtrin** [comment]
Was this ever looked at? This is a great tool but I'm having to consider turning it off due to reconciliation storm it causes
