### ISSUE TITLE
Version command doesn't print correct information

### ISSUE THREAD

**Issue by perios101** [FairwindsOps/goldilocks#463]
### What happened?

Running `goldilocks version` prints out following:

`Version:$(VERSION) Commit:$(COMMIT)`

Tested behaviour in versions 4.3.0_darwin_arm64 and 4.3.1_darwin_arm64

### What did you expect to happen?

Actual version output along with a correct hash as per release info [here](https://github.com/FairwindsOps/goldilocks/releases/tag/v4.3.1)

### How can we reproduce this?

Download [4.3.1 darwin arm64 binary](https://github.com/FairwindsOps/goldilocks/releases/download/v4.3.1/goldilocks_4.3.1_darwin_arm64.tar.gz)

Run `goldilocks version` command using the above binary.

### Version

4.3.1_darwin_arm64, 4.3.0_darwin_arm64

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by transient1** [comment]
Thanks for pointing this out. We'll work on getting this fixed.
