### ISSUE TITLE
Support for multi container pods

### ISSUE THREAD

**Issue by ceastman-r7** [FairwindsOps/goldilocks#472]
**Is your feature request related to a problem? Please describe.**
I have Istio installed which injections a 2nd container into the pods. https://istio.io/latest/about/service-mesh

**Describe the solution you'd like**
It would be good to have recommendations per container per pod.

**Comment by sudermanjr** [comment]
This is already supported. Please see the attached screenshot. 

![Screen Shot 2022-05-26 at 1 47 03 PM](https://user-images.githubusercontent.com/7624765/170565680-3491ccc0-996a-4808-9039-d2fead5a4aa9.png)

**Comment by ceastman-r7** [comment]
Hmm, when I tried it only showed one container in the pod even though the Istio sidecar was in the pod also. Did I need to wait longer for vpa to process? Or is there a log I could check?

**Comment by sudermanjr** [comment]
Ah, you mentioned Istio. I forgot by default we have added the exclude flag for istio sidecars:

`-e, --exclude-containers string   Comma delimited list of containers to exclude from recommendations.`

https://github.com/FairwindsOps/charts/blob/850e0b3b0f0a262b0ddc916fe2cb0e82eee92013/stable/goldilocks/values.yaml#L108

**Comment by ceastman-r7** [comment]
Why would the istio sidecar be excluded?

**Comment by sudermanjr** [comment]
At the time, we decided to exclude it by default because it is a lot of noise in an environment where we are most focused on apps and their behavior.

It is easily re-included by setting that value, and I definitely think doing so is a great idea!
