### ISSUE TITLE
Hide "Detail All Namespaces" dashboard menu

### ISSUE THREAD

**Issue by PedroAlbamonte** [FairwindsOps/goldilocks#480]
I would like to know if there is already an option, flag or configuration to hide the "Detail All Namespaces" menu on the dashboard?

As I have several namespaces, this menu takes a long time to respond and causes an "OOMKilled" in the POD (I could increase the POD's memory, but my intention is that they only query one namespace at a time)

**Comment by sudermanjr** [comment]
This is not currently an option in the dashboard.
