### ISSUE TITLE
Goldilocks in GKE with Google's VPA beta...prometheus not supported, but is it taking advantage of cloud metrics historical data?

### ISSUE THREAD

**Issue by kherrmann3** [FairwindsOps/goldilocks#484]
My understanding is that Goldilocks is wholly dependent on the underlying VPA structure for the recommendations. And that the GKE VPA Beta doesn't enable integrations with Prometheus. 

But, since Google claims that their VPA takes advantage of historical metrics in a similar manner, does that mean that Goldilocks is, as well? I'd assume as much, but since they don't actually deploy VPA objects (from what I can see) hoping to get clarification there.

**Comment by sudermanjr** [comment]
Yep, you are correct. Goldilocks is 100% dependent on VPA, so if the GKE VPA is indeed using historical metrics, then Goldilocks will as well.

**Comment by kherrmann3** [comment]
Thanks! I'm tempted to avoid the Google VPA, mainly because it feels like such a black box. But, it's probably good enough, for where we are at.
