### ISSUE TITLE
dashboard.basePath in Helm chart not working

### ISSUE THREAD

**Issue by cmukai-cisco** [FairwindsOps/goldilocks#499]
I tried to use the dashboard.basePath in the goldilocks Helm chart and got the following error in the container logs:
```
Error: unknown flag: --base-path
```
Can this feature be implemented?

**Comment by sudermanjr** [comment]
Can you please share the version of the chart and the image version that is running in the cluster?

**Comment by cmukai-cisco** [comment]
Wow, that was fast. Here is the requested information:

Chart: 6.1.4
Image tag: v4.3.3


From: Andrew Suderman ***@***.***>
Date: Wednesday, August 3, 2022 at 10:26 AM
To: FairwindsOps/goldilocks ***@***.***>
Cc: Conrad Mukai (cmukai) ***@***.***>, Author ***@***.***>
Subject: Re: [FairwindsOps/goldilocks] dashboard.basePath in Helm chart not working (Issue #499)

Can you please share the version of the chart and the image version that is running in the cluster?

**Comment by sudermanjr** [comment]
Thanks for the info. There's definitely something odd about this latest helm chart. I'm looking into it.

**Comment by sudermanjr** [comment]
Hmm, somehow we didn't actually release the basePath functionality, but added it to the helm chart. I'm releasing a new version of Goldilocks now, and I'll push a chart PR as well.

**Comment by cmukai-cisco** [comment]
Is there an ETA for the basePath feature?

**Comment by cmukai-cisco** [comment]
Its working. Thanks for the quick response.
