### ISSUE TITLE
Need to round the cost data, or not show scientific notation

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/goldilocks#535]
### What happened?

![Screen Shot 2022-10-07 at 11 14 42 AM](https://user-images.githubusercontent.com/7624765/194613551-7cabb4e0-01e7-4eee-b7f6-592e124bfea3.png)

### What did you expect to happen?

A more human-readable cost estimate.

### How can we reproduce this?

Fire up goldilocks and get cost data.

### Version

v4.5.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpelletier1** [comment]
+1 to this
