### ISSUE TITLE
"emailInput is null" error on namespaces list page

### ISSUE THREAD

**Issue by thewildmage** [FairwindsOps/goldilocks#542]
### What happened?

Just by being on the home page (`/namespaces`), there's an "Uncaught TypeError: emailInput is null" error in the console. This appears to be caused by the fact that the `self-identification.js` script is included in the `<head>` of this page and is looking for an HTML element that doesn't exist.

### What did you expect to happen?

I would expect no errors in the console.

Also, it doesn't appear that the `self-identification.js` script is needed on the `/namespaces` page, so maybe it should be removed from there?

### How can we reproduce this?

Go to Goldilocks' home page (which is `/namespaces`) and open the Console tab of the Developer Tools.

### Version

v4.5.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
This may have been fixed in #546

**Comment by sudermanjr** [comment]
Confirmed fixed.
