### ISSUE TITLE
controller logs errors trying to update outdated revision of VPAs

### ISSUE THREAD

**Issue by stevo-f3** [FairwindsOps/goldilocks#565]
### What happened?

Too frequently in controller logs one can find errors like:
```
E1216 16:10:33.149195       1 vpa.go:321] Error updating VPA/foo in Namespace/bar: Operation cannot be fulfilled on verticalpodautoscalers.autoscaling.k8s.io "foo": the object has been modified; please apply your changes to the latest version and try again
E1216 16:10:33.149215       1 pod.go:48] Error reconciling: Operation cannot be fulfilled on verticalpodautoscalers.autoscaling.k8s.io "foo": the object has been modified; please apply your changes to the latest version and try again
```

Is there some concurrency issue? Maybe issue upstream so outdated controller libraries like https://github.com/FairwindsOps/goldilocks/issues/555?

### What did you expect to happen?

No such errors in logs

### How can we reproduce this?

Not really sure how to reproduce. Maybe it's triggered when having enough of VPAs.

Context:
- goldilocks v4.5.1 and chart 6.3.3
- k8s 1.24
- number of VPAs between 300 - 700, all in recommender mode only

### Version

https://github.com/FairwindsOps/charts/tree/master/stable/goldilocks 6.3.3 with vpa subchart enabled

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
This is a common issue with controllers. I think there is a way to at least suppress the logging or ignore those specific update events.

**Comment by ContainerNerd** [comment]
comment to remove stale state
