### ISSUE TITLE
Next version after 3.7.4

### ISSUE THREAD

**Issue by arthurngatat** [FairwindsOps/goldilocks#576]
Hello my comapny is looking to update goldilocks. We are currently using version 3.7.4 can you please let me know what is the next version after v3.7.4?

**Comment by sudermanjr** [comment]
Hi! You can see the full list of releases [here](https://github.com/FairwindsOps/goldilocks/releases)

The helm chart has a different set of releases that are independent of Goldilocks itself. We recommend the latest version listed [here](https://github.com/FairwindsOps/charts/blob/07ee997203cf345d092fa4811fd3494c0c72ca16/stable/goldilocks/Chart.yaml#L3)
