### ISSUE TITLE
Modify recommender minimum and maximum value

### ISSUE THREAD

**Issue by LorenzoAstengo** [FairwindsOps/goldilocks#579]
It would be very convenient to have the possibility to set the minimum and maximum values that goldilocks can recommend, as for example it is possible to do by using the classic vpas.

Thank you.

**Comment by sudermanjr** [comment]
Hi there! 

This used to be a flag you could specify on the VPA recommender, but it seems in the newer versions that is on the VPA object itself.  I'll leave this as an enhancement and see if we can look at updating our VPA dependency.
