### ISSUE TITLE
Please add the /api endpoint functionality back in

### ISSUE THREAD

**Issue by hickert33** [FairwindsOps/goldilocks#585]
It seems the /api endpoint has been dropped in recent releases, we would like to have it added back in if you can. I confirmed it was removed with Andy Suderman in the Fairwinds community slack.

Our use-case is such that we have some code that runs in our ci pipelines that will hit the /api for the namespace and do some logic to tell our devs to increase/decrease requests/limits for cpu/mem.   It decorates the PR with a report with the details. 

When I upgrade goldilocks, of course it breaks our use case, so we have backed out our upgrade for now so that we can have this what we call "Goldilocks Analysis" PR decoration continue to work.

Thank you for considering this,
Ed

**Comment by jpelletier1** [comment]
@hickert33 Great feedback! Thank you for this. Our team is looking at bringing this back.

I'd love to dig into a bit more about your CI use case. Few questions...
- Implementation wise, does your CI script parse your YAML code to extract namespace/workload metadata?
- Does your script have some sort of tolerance between what's currently set as request/limits and what goldilocks is recommending?
- If you could wave a magic wand, what else would you like Goldilocks to do for you at the CI stage?

**Comment by hickert33** [comment]
@jpelletier1    To answer your questions:

- Its basically pulling the recommendations vs the actual and putting a report on the PR with color coded dot (red for underprovisioned, yellow for overprovisioned, question mark if they dont' have request/limits defined, and green if its good to go).   
- To make it green report (ok) it is has a small percent tolerence to what goldilocks recommends.
- I don't think anything, we are basically just putting a pretty report on the pr's to remind the devs to set/review requests/limits, then they go into goldilocks dash directly from a link and can see the reccomendations.

**Comment by jpelletier1** [comment]
@hickert33 Thank you for that background! We are considering two new features in our commercial product, Fairwinds Insights:

1. Automated PRs w/ fixes: this would create an automated "fix" PRs with the recommended requests/limits, saving developers a few clicks from having to look into the dashboard for each workload.
2. Cost estimates at time of PR: get a comment on your PR with the estimated cost of a workload based on the configured requests/limits

Curious if you'd find any of these things valuable?
