### ISSUE TITLE
504 Timeout on dashboard - namespace detail / There are 0 vpas

### ISSUE THREAD

**Issue by aradhell** [FairwindsOps/goldilocks#618]
### What happened?

Click to namespace and got 504 timeout error, also see log from controller : 
There are 0 vpas in {namespace}, 
{namespace} is not managed

labeled related namespace with `kubectl label ns {namespace} goldilocks.fairwinds.com/enabled=true`

I tried to label again with same command: it now returns namespace/{namespace} not labeled

### What did you expect to happen?

Show namespace detail page

### How can we reproduce this?

Maybe testing with a namespace with 100+ deployment, 20+ cronjobs etc.

### Version

fairwinds-stable/goldilocks

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Usually this happens because the Dashboard gets oomKilled in large clusters. Can you please share the output of `kubectl describe pod goldilocks-dashboard` and any relevant log messages from the controller and the dashboard?

**Comment by sudermanjr** [comment]
As I suspected, the dashboard is being OOMKilled:

```
 Last State:     Terminated
      Reason:       OOMKilled
```

I would recommend increasing the memory limit for the dashboard pod.

**Comment by aradhell** [comment]
Thanks for the recommendation @sudermanjr , increased memory and dashboard works now, but it doesn't create any VPA.

```
 k get vpa -A                                               
NAMESPACE    NAME                               MODE   CPU   MEM   PROVIDED   AGE
goldilocks   goldilocks-goldilocks-controller   Off                           20h
goldilocks   goldilocks-goldilocks-dashboard    Off                           20h
```


```
I0628 17:11:42.175230       1 controller.go:184] namespace/bowtie has been added.
I0628 17:11:42.274158       1 controller.go:60] Watcher synced.
I0628 17:11:42.575321       1 namespace.go:35] Namespace bowtie updated. Check the labels
```
