### ISSUE TITLE
Option to disable `email` template on dashboard

### ISSUE THREAD

**Issue by mikutas** [FairwindsOps/goldilocks#630]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/FairwindsOps/goldilocks/assets/23391543/8c20bb40-e956-42db-9f06-378ceb5a9066)

To be honest, if the advertising email form was't at the top of the page, we could enjoy better experience of dashboard.

**Describe the solution you'd like**

Add new flag of `dashboard` command to disable rendering `email` template

**Describe alternatives you've considered**

Just move the form to the bottom of the page

**Additional context**

**Comment by sudermanjr** [comment]
I am definitely good with adding the ability to disable this functionality for those that don't want to use it. I would suggest a boolean flag on the dashboard called `--cost-enabled` that defaults to `false`

**Comment by et304383** [comment]
@sudermanjr can we get this incorporated into the helm chart?
