### ISSUE TITLE
Do not create VPA for a workload if an HPA or VPA already exists

### ISSUE THREAD

**Issue by max0ne** [FairwindsOps/goldilocks#655]
**Is your feature request related to a problem? Please describe.**
For workloads where HPAs or VPAs are already created, Goldilocks should avoid creating VPAs for them.

If a workload already has a VPA created, currently Goldilocks still creates a VPA for that workload, potentially overwriting the existing resource, or creating a conflicting VPA.

If a workload already has a HPA created, and the HPA works based on CPU or memory, Goldilocks should also avoid creating VPA for it, because it's a [known limitation](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#known-limitations):
> Vertical Pod Autoscaler should not be used with the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics) (HPA) on CPU or memory at this moment. However, you can use VPA with [HPA on custom and external metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-on-custom-metrics).

**Describe the solution you'd like**

Goldilocks controller will need to keep track of existing VPAs and HPAs in the cluster, maps them to all discovered workloads, use this information to determine if it should create VPA for each workload.

Additionally, when user creates a conflicting HPA or VPA object, Goldilocks should also cleanup its managed HPA and VPA objects

**Comment by sudermanjr** [comment]
I have a couple questions/concerns about this, and the proposed implementation.

> If a workload already has a VPA created, currently Goldilocks still creates a VPA for that workload, potentially overwriting the existing resource

This is false, unless for some reason you are manually creating VPAs that are prefixed with `goldilocks-`, which would be... odd?

> or creating a conflicting VPA.

Only in the case of using VPAs in non-off mode, which is not the original intended use-case for Goldilocks. 

- Why would an end user enable Goldilocks in a namespace where they are managing their own VPAs? This seems like optimizing for an unintended use-case
- What about the case where a goldilocks managed vpa is in recommend (off) mode, and it is prefixed with goldilocks-. This has no impact to existing VPAs and can provide meaningful information on the dashboard.
- How will this change in behavior be reflected in the dashboard? 
- We are planning to add [this PR](https://github.com/FairwindsOps/goldilocks/pull/641) where the  dashboard provides a warning to the user if they are using an HPA, this will overlap with or eliminate that functionality, and should be considered.


In general, I would like to work towards supporting more VPA use-cases, but this is a very large change to how Goldilocks currently functions and is intended to be used, so I want to be diligent about answering all these questions and considering all the tradeoffs before making such a large change.
