### ISSUE TITLE
Question: Get summary

### ISSUE THREAD

**Issue by dkirrane** [FairwindsOps/goldilocks#656]
I see the CLI usage is not recommended 
https://goldilocks.docs.fairwinds.com/advanced/#cli-usage-not-recommended

My question is is there another way to get a Summary report of all VPA recommendations? I've deployed using the Helm chart in recommender mode
https://goldilocks.docs.fairwinds.com/advanced/#summary

**Comment by sudermanjr** [comment]
CLI usage isn't recommended simply because we don't optimize for end-user CLI usage. However, the summary command does generate the JSON that feeds the dashboard, so for the purpose of just generating a blob of data it's perfectly fine.
