### ISSUE TITLE
Display resource quota of the namespace

### ISSUE THREAD

**Issue by bighiro** [FairwindsOps/goldilocks#657]
**Is your feature request related to a problem? Please describe.**
Currently, there is no where the resource quota applied on the namespace is displayed.
If it is displayed on the dashboard it would be easier to know the quota report.

**Describe the solution you'd like**
The resource quota could be displayed on the namespace dashboard (If resource quota configured)

**Describe alternatives you've considered**

**Additional context**

**Comment by bodgit** [comment]
Possibly related, it would be nice to see an overall Namespace view, i.e. total resources currently used vs how much if all of the recommendations were applied within that Namespace. That would make it easier to see which were the most misconfigured.
