### ISSUE TITLE
goldilocks-vpa-recommender restarts all the time 

### ISSUE THREAD

**Issue by liorco300** [FairwindsOps/goldilocks#672]
### What happened?

Warning  Unhealthy  2m49s (x1441 over 22h)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 500                                                                                               
Warning  Unhealthy  2m49s (x1443 over 22h)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500

### What did you expect to happen?

used latest helm chart
Client Version: v1.25.10
Kustomize Version: v4.5.7
Server Version: v1.25.10-gke.2700

### How can we reproduce this?

i just installed the chart

- helm repo add fairwinds-stable https://charts.fairwinds.com/stable
- helm repo update
- helm upgrade --install goldilocks --namespace goldilocks --set vpa.enabled=true  --set controller.flags.on-by-default=true  --set controller.flags.exclude-namespaces=["kube-system"] --set dashboard.flags.on-by-default=true fairwinds-stable/goldilocks --namespace goldilocks --create-namespace || true

### Version

latest

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

latest log 

`latest log:
`I1128 15:07:13.958370       1 reflector.go:559] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:136: Watch close - *v1.DaemonSet total 6 items received
I1128 15:07:19.245557       1 reflector.go:559] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/api.go:88: Watch close - *v1.VerticalPodAutoscaler total 7 items received
I1128 15:07:27.753488       1 reflector.go:559] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:136: Watch close - *v1.Job total 7 items received``

**Comment by sudermanjr** [comment]
This is usually caused by CPU throttling. I would recommend checking your resource requests and limits.

**Comment by liorco300** [comment]
Hi doubled the resources and no throttling in cpu:

vpa:
  enabled: true
  recommender:
    enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 2000Mi
      requests:
        cpu: 500m
        memory: 1000Mi

restarts still happening:
from logs i see client side throttling :
` 1 request.go:622] Waited for 197.233942ms due to client-side throttling, not priority and fairness, request: GET:https:/x.x.x.x:443/apis/autoscaling.k8s.io/v1/namespaces/xxxxx       1 reflector.go:559] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go:171: Watch close - *v1.Pod total 12 items received
`
