### ISSUE TITLE
[RFE] HTML anchors for specific workload in namespace

### ISSUE THREAD

**Issue by evgkrsk** [FairwindsOps/goldilocks#674]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated by fact that there is no way to point out to goldilocks recommendations for specific workload, only to whole ns.

**Describe the solution you'd like**
Generate anchors in HTML code so one can point browser to something like http://goldilocks.foo.bar/dashboard/kube-system#calico-node to get page scrolled down and container "calico-node" expanded for view.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sudermanjr** [comment]
I could see this being useful if someone wanted to implement it.
