### ISSUE TITLE
For different Kinds with same name, only one VPA created

### ISSUE THREAD

**Issue by evgkrsk** [FairwindsOps/goldilocks#676]
### What happened?

We have coredns deployed both as deployment and daemonset in one ns. In goldilocks dashboard, there is only recommendations for daemonset. In ns, there is only one VPA: goldilocks-coredns with daemonset as targetRef.

### What did you expect to happen?

We expected to have separated recommendations for deployments AND daemonset coredns. In ns, there must be two separate VPA objects for different coredns kinds.

### How can we reproduce this?

- Deploy coredns as deployments in ns kube-system (assuming that by default it is already deployed as daemonset)
- Enable goldilocks handing of this ns
- Observe results in dashboard.

### Version

goldilocks:v4.10.0 image in controller/dashboard, vpa-recommender:0.14.0 image

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Oh that's an interesting bug. Sounds like we need some additional test cases.

**Comment by evgkrsk** [comment]
Seems like there is random choice of kind: goldilocks creates vpa for daemonset in one cluster and for deployment in another (similar ds/deploy coredns instances).
