### ISSUE TITLE
istio-proxy not shown

### ISSUE THREAD

**Issue by erikkn** [FairwindsOps/goldilocks#688]
Afternoon, folks!

I am running Goldilocks 4.10.1 and VPA 1.0.0 (only vpa-recommender enabled). Please consider the following VPA object:

```
Spec:
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         foobar
  Update Policy:
    Update Mode:  Off
Status:
  Conditions:
    Last Transition Time:  2024-01-16T15:39:09Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  istio-proxy
      Lower Bound:
        Cpu:     20m
        Memory:  115123105
      Target:
        Cpu:     23m
        Memory:  126805489
      Uncapped Target:
        Cpu:     23m
        Memory:  126805489
      Upper Bound:
        Cpu:           1161m
        Memory:        6405312222
      Container Name:  foobar
      Lower Bound:
        Cpu:     9m
        Memory:  464624172
      Target:
        Cpu:     11m
        Memory:  511772986
      Uncapped Target:
        Cpu:     11m
        Memory:  511772986
      Upper Bound:
        Cpu:     555m
        Memory:  25851134585
Events:          <none>
```

Please consider the following goldilocks-dashboard running configuration

```
    Command:
      /goldilocks
      dashboard
      --exclude-containers=bla
      -v2
```

When I check the Goldilocks dashboard, the `istio-proxy` container is not shown. Do you have any idea what might be causing this?

**Comment by sudermanjr** [comment]
By default in the values file we exclude those containers. You can override it here https://github.com/FairwindsOps/charts/blob/e19ce64430ad71adedf93fd6438f4de1770326f1/stable/goldilocks/values.yaml#L116

**Comment by erikkn** [comment]
@sudermanjr I have this disabled, my running config is the following:

```
    Command:
      /goldilocks
      dashboard
      --exclude-containers=bla
      -v2
```

**Comment by ciaccotaco** [comment]
Hello,

We are affected by the same issue.  It would be nice to display istio-proxy recommendations through the Goldilocks dashboard.

While the VPA shows the recommendation, it is omitted from the dashboard due to the code only looping through the containers defined in the workload spec ([see here](https://github.com/FairwindsOps/goldilocks/blob/v4.13.2/pkg/summary/summary.go#L210-L226).  Any container that is injected via the mutating webhook is ignored.
