### ISSUE TITLE
VPA Mode: Auto

### ISSUE THREAD

**Issue by openstep** [FairwindsOps/goldilocks#697]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add the possibility to set the VPA Mode: Auto? Currently it is Off.

**Describe the solution you'd like**
I would like to be able to turn the VPA mode to Auto so the VPA would be able to scale pods.

**Comment by divyanjali1** [comment]
Is this feature available in VPA chart ? 
I am manually adding the label to all namespaces as of now to set the update mode to "auto"
kubectl label ns goldilocks goldilocks.fairwinds.com/vpa-update-mode="auto"

**Comment by mamutuberalles** [comment]
Yeah, that is not available from the manifest, you have to annotate the workloads, and label the namespaces.
