### ISSUE TITLE
Legend or tooltip for symbols

### ISSUE THREAD

**Issue by celik-sr** [FairwindsOps/goldilocks#709]
I want to understand the symbols used in the Goldilocks UI. I have the following recommendation and need clarification on the meaning of the exclamation for CPU Request in this context and whether the recommendation is valid or if the exclamation indicates an error generating the recommendation.
![Screenshot 2024-06-12 at 11 42 06](https://github.com/FairwindsOps/goldilocks/assets/162155972/a55220ec-bc24-4801-920d-71c26fb330c8)

**Comment by sudermanjr** [comment]
Exclamation is intended to mean not equal. I believe there should be alt-text for the icons to indicate that.

**Comment by celik-sr** [comment]
Is "not equal" used when the values are within some threshold? Why is `<` or  `>` insufficient to indicate Current vs Burstable?

**Comment by sudermanjr** [comment]
There's a whole history with burstable and how we display that. There's not really any way that we've tried that someone doesn't find an issue with. 

I would focus on the guaranteed numbers anyway, they're better. :-D

**Comment by sudermanjr** [comment]
To answer your question - not equal is used when they are explicitly not equal

**Comment by celik-sr** [comment]
Thank you for the clarification. I'm going to close this.
