### ISSUE TITLE
The goldilock dasboard is not displaying all containers in namespace

### ISSUE THREAD

**Issue by meadows12** [FairwindsOps/goldilocks#729]
### What happened?

I have enabled Goldilocks for all namespaces in the cluster, but I am not receiving recommendations for all containers in the dashboard. Only one container is missing, and I see this error in the dashboard logs: `no matching Workloads found for VPA/goldilocks-webhook-portal.`

When I checked the VPA Custom Resource Definition (CRD), I found that the VPA for this container has already been created with the appropriate recommendation.

### What did you expect to happen?

The goldilock dashboard should display all the containers in namespace 

### How can we reproduce this?

- Install goldilocks and vpa-recommender using helm chart and enable it for all the namespaces. 
- Check if you get the recommendation of all the containers in the dashboard. If not, check the logs of dashboard/ goldilock-controller and also check if the VPA is created for each of the container in the namespace. 

### Version

9.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
If the VPA is there, it is very unusual for the dashboard not to display it. However, reproducing this will be very difficult without a lot more detail. First step would be to turn up the logging on the dashboard, share those logs, and then share the full YAML of the workload and the VPA that was created.

**Comment by meadows12** [comment]
Hey @sudermanjr, attaching logs from dashboard and VPA that was created 

```
I0930 20:35:29.709528       1 dashboard.go:64] Starting goldilocks dashboard server on port 8080 and basePath /
E1001 05:55:32.790906       1 summary.go:162] no matching Workloads found for VPA/goldilocks-db-init
E1001 05:55:32.888959       1 summary.go:162] no matching Workloads found for VPA/goldilocks-webhook-portal
```
And this is the VPA created 
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  creationTimestamp: '2024-09-05T09:56:10Z'
  generation: 4
  labels:
    creator: Fairwinds
    source: goldilocks
  managedFields:
    - apiVersion: autoscaling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:creator: {}
            f:source: {}
        f:spec:
          .: {}
          f:targetRef: {}
          f:updatePolicy:
            .: {}
            f:updateMode: {}
      manager: goldilocks
      operation: Update
      time: '2024-09-18T13:08:38Z'
    - apiVersion: autoscaling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:recommendation:
            .: {}
            f:containerRecommendations: {}
      manager: recommender
      operation: Update
      subresource: status
      time: '2024-10-01T05:55:59Z'
  name: goldilocks-webhook-portal
  namespace: webhook
  resourceVersion: '2033106836'
status:
  conditions:
    - lastTransitionTime: '2024-09-05T09:57:00Z'
      status: 'True'
      type: RecommendationProvided
  recommendation:
    containerRecommendations:
      - containerName: m2ee-sidecar
        lowerBound:
          cpu: 10m
          memory: '52428800'
        target:
          cpu: 11m
          memory: '52428800'
        uncappedTarget:
          cpu: 11m
          memory: '52428800'
        upperBound:
          cpu: 11m
          memory: '52428800'
      - containerName: mendix
        lowerBound:
          cpu: 22m
          memory: '716657383'
        target:
          cpu: 23m
          memory: '716711186'
        uncappedTarget:
          cpu: 23m
          memory: '716711186'
        upperBound:
          cpu: 23m
          memory: '743613777'
spec:
  targetRef:
    apiVersion: ***
    kind: ***
    name: webhook-portal
  updatePolicy:
    updateMode: 'Off'
```
And what do you mean by the YAML of the workload exactly ?

**Comment by meadows12** [comment]
@sudermanjr btw, the kind of this is custom RD created of our own. Not any Kubernetes resources. Would that be an issue ?

**Comment by meadows12** [comment]
@sudermanjr could you check and help in any way ?
