### ISSUE TITLE
Make units consistent

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/goldilocks#78]
If the units are currently set in e.g. `Mi`, we should round the recommendation (which seems to always be in `k` for memory).

This way, the dashboard will be more readable (no more `128Mi < 262144k`), and any copy/pasted config will stick to the user's current unit conventions.

<img width="357" alt="Screen Shot 2019-10-15 at 10 58 00 AM" src="https://user-images.githubusercontent.com/7611973/66843638-0fe0a400-ef3b-11e9-8def-418730216bb9.png">

**Comment by sudermanjr** [comment]
This would be super annoying to implement.  This is the info that the Kube objects (vpa and deployment) return.  It's do-able, but the types for this are difficult to work with.

**Comment by robscott** [comment]
It was definitely a pain to deal with this interface for kube-capacity. I'm not sure how easy it is to actually know the format the request was set in, but it's not that bad to just print out memory with Mi units like elsewhere in the k8s codebase. Here's the code behind [kubectl top](https://github.com/kubernetes/kubectl/blob/master/pkg/metricsutil/metrics_printer.go#L319) that formats resources, I used this same approach for kube-capacity for whatever that's worth.

**Comment by rbren** [comment]
This should help as well: https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity.RoundUp
