### ISSUE TITLE
Support Daemonsets

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/goldilocks#84]
Currently Goldilocks will not create VPAs for DaemonSets. We should enable this.

Possible parts of this feature:

- [ ] enable or disable daemonset controller with a flag
- [ ] Container exclusions should apply to DaemonSets the same way they do Deployments
- [ ] Enable or disable deployments with a flag to set a pattern for additional types

**Comment by sudermanjr** [comment]
Example of a VPA targeting a DS:

```

**Comment by bootc** [comment]
Bump to freshen

**Comment by raspberrypython** [comment]
PR #116 submitted for DaemonSet support

**Comment by sudermanjr** [comment]
closing in favor of #225
