### ISSUE TITLE
Support StatefulSets

### ISSUE THREAD

**Issue by bootc** [FairwindsOps/goldilocks#96]
Similarly to #84 it would be really useful to have support for pods descending from StatefulSet resources.

**Comment by sudermanjr** [comment]
Thanks for the request! We will see if we can get this added to the roadmap at some point.

**Comment by bootc** [comment]
Bump to freshen

**Comment by sarahhenkens** [comment]
Bump up on this @sudermanjr, are there any plans to add the outstanding feature requests?

**Comment by chris-morandi** [comment]
Would like this too, i.e. statefulset support

**Comment by sudermanjr** [comment]
closing in favor of #225
