### ISSUE TITLE
Update CLA Link

### ISSUE THREAD

**Issue by hjkatz** [FairwindsOps/goldilocks#98]
I'd like to contribute to this project and want to sign the CLA as documented in CONTRIBUTING.md, however the CLA link is a 404 atm: https://cla-assistant.io/fairwindsops/goldilocks

**Comment by ejether** [comment]
Hi @hjkatz , Thanks for pointing this out. It should be fixed now. Please feel free to reopen the issue if it persists.

**Comment by hjkatz** [comment]
Thanks for the quick update!
